trigger:
  batch: true
  branches:
    include:
    - master
    - release/*

pr:
- master
- release/*

pool: Linux

resources:
  repositories:
  - repository: templates
    type: github
    name: unmango/azure-pipelines-templates
    endpoint: unmango

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  Pool: Linux
  BuildConfiguration: Release
  PackageName: Packages
  CI: true

jobs:
- template: /jobs/dotnet/nuget-package.yml@templates
  parameters:
    pool: Linux
    projects: src/**/*.csproj
    nugetConfig: NuGet.Config
    externalFeedCredentials: 'UnMango GitHub NuGet'
    artifactName: UnMango.Rest

    preRestore:
    - script: dotnet tool restore --ignore-failed-sources
      displayName: Restore .NET tools

    postBuild:
    - template: /steps/dotnet/test.yml
      parameters:
        projects: '**/test/**/*.csproj'
        buildProjects: false
        installReportGenerator: false

- template: /jobs/nuget/push.yml@templates
  parameters:
    pool: Linux
    environment: GitHub
    feed: 'UnMango GitHub NuGet'
    artifact: UnMango.Rest
    dependsOn: pack_dotnet_nuget_package
    condition: |
      or(
        contains(variables['Build.SourceBranch'], 'master'),
        contains(variables['Build.SourceBranch'], 'release')
      )
