version: 1

update_configs:
- package_manager: dotnet:nuget
  directory: "/src/UnMango.Rest"
  update_schedule: live
  automerged_updates:
  - match:
      dependency_type: all
      update_type: semver:minor

- package_manager: dotnet:nuget
  directory: "/test/UnMango.Rest.Test"
  update_schedule: live
  automerged_updates:
  - match:
      dependency_type: all
      update_type: semver:minor

#- package_manager: dotnet:nuget
#  directory: "/test/UnMango.Rest.Benchmarks"
#  update_schedule: live
#  automerged_updates:
#    - match:
#        dependency_type: all
#        update_type: semver:minor
